const SEARCH_MOVIES = "SEARCH_MOVIES";
const ADD_TO_LIST = "ADD_LIST";
const DELETE_MOVIE = "DELETE_MOVIE";
const ADD_MOVIE_REVIEW = "ADD_MOVIE_REVIEW";
const UPDATE_MOVIES_TOP_WEEK = "UPDATE_MOVIES_TOP_WEEK";
const UPDATE_MOVIES_TOP_DAY = "UPDATE_MOVIES_TOP_DAY";
const DELETE_REVIEW = "DELETE_REVIEW";
const MOVIE_STATE = "MOVIE_STATE";

export {
  SEARCH_MOVIES,
  ADD_TO_LIST,
  DELETE_MOVIE,
  ADD_MOVIE_REVIEW,
  UPDATE_MOVIES_TOP_WEEK,
  UPDATE_MOVIES_TOP_DAY,
  DELETE_REVIEW,
  MOVIE_STATE,
};
