const SEARCH_MOVIES = "SEARCH_MOVIES"
const ADD_TO_LIST = "ADD_LIST"
const DELETE_MOVIE = "DELETE_MOVIE"
const ADD_MOVIE_REVIEW = "ADD_MOVIE_REVIEW"

export {SEARCH_MOVIES, ADD_TO_LIST, DELETE_MOVIE, ADD_MOVIE_REVIEW}